#ifndef DEVICE_H
#define DEVICE_H

enum {
    FUZZ_DEVICE_MAKE_SNAPSHOT = 0,
    FUZZ_DEVICE_ADD_CMP_ARRAY=12,
    FUZZ_DEVICE_RESET=16,
    FUZZ_DEVICE_ADD_INPUT_REGION=20,
    FUZZ_DEVICE_GET_INPUT=24,
    FUZZ_DEVICE_ADD_OUTPUT_REGION=28,
    FUZZ_DEVICE_ADD_REMOTE_COV_ARRAY=32,
    FUZZ_DEVICE_ADD_PFN_BASE=36,
    FUZZ_DEVICE_ADD_PFN_SIZE=40,
    FUZZ_DEVICE_SHOW_TRACE=44,
    FUZZ_DEVICE_SET_KCOV_TIMER=48,
    FUZZ_DEVICE_ADD_SYSCALL_LOG=52,
    FUZZ_DEVICE_ADD_STR0=56,
    FUZZ_DEVICE_ADD_STR1=60,
    FUZZ_DEVICE_STRCMP=64,
    FUZZ_DEVICE_ABORT_INPUT=68,
    FUZZ_DEVICE_OPS_END
};

#endif
